### ISSUE TITLE
anacondaのundefinedエラーが発生する

### ISSUE THREAD

**Issue by nirot1r** [nirot1r/JoinT-BE#1]
## コミット
https://github.com/nirot1r/JoinT-BE/commit/3e6024c9d3d626fb1d5a3a86dec5cb16a260311c anacondaのundefinedエラーが発生する

## 出力
```bash
nirot1r@vivobook ~/go/src/github.com/nirot1r/JoinT-BE $ go run main.go
# command-line-arguments
./main.go:31:23: undefined: anaconda.AuthorizationURL
./main.go:41:15: undefined: anaconda.GetCredentials
```

**Comment by TinyKitten** [comment]
https://github.com/ChimeraCoder/anaconda/blob/master/twitter.go#L13
https://github.com/ChimeraCoder/anaconda/blob/master/twitter.go#L191
